### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by miladganjali** [bugphix/bugphix-laravel#6]
I installed the package and run test there is no problem but when I go to default URL there is nothing there except this code 

```
<!DOCTYPE html>
  <html lang="en">
  <head>
  <title>Bugphix</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="8ibmuQ7CVHrce6ep7l78ChG0XJ8wD4vv3uJaNFnv">
```

there is no body tag.

another thing after installation

`php artisan route:list
`
is not working and shows nothing when I remove this package the command work again.

**Client / Server details**
 - Server OS: windows
 - Browser chrome
 - Laravel version 7

**Comment by jericizon** [comment]
hello, could you elaborate more about the error you encounter? i tried to install it on fresh laravel 7 and it seems working fine.

For installation just follow the steps: https://bugphix-docs.netlify.com/installation/#server-requirements

**Comment by miladganjali** [comment]
I follow the installation path on the page that you mentioned.
another thing that I forget to tell you about there is a difference between that page and the GitHub readme page. on that page, this part is missing

> Application usage
> edit: /app/Exceptions/Handler.php
> 
> ```
> public function report(Exception $exception)
> {
>     if (app()->bound('bugphix') && $this->shouldReport($exception)) {
>         app('bugphix')->catchError($exception);
>     }
> 
>     parent::report($exception);
> }
> ```
and yes I tried both of them and github page works but with above bug.
and how should I elaborate more there is no error even on the server just the part that I mentioned above.

**Comment by OoHerbethoO** [comment]
I'm also having problems, and I discovered the following system error: 
**WhoopsRun::handleError("Trait method getEventUrl has not been applied, because there are collisions with other trait methods on BugphixBugphixLaravelTraitsBugphixProcess", ".../vendor/bugphix/bugphix-laravel/src/Traits/BugphixProcess.php")**

**Comment by miladganjali** [comment]
@OoHerbethoO 
you can put this code on 
the error is getting away but the result is just not working

edit: /app/Exceptions/Handler.php
```
public function report(Exception $exception)
{
    if (app()->bound('bugphix') && $this->shouldReport($exception)) {
        app('bugphix')->catchError($exception);
    }

    parent::report($exception);
}
```

**Comment by OoHerbethoO** [comment]
> @OoHerbethoO
> you can put this code on
> the error is getting away but the result is just not working
> 
> edit: /app/Exceptions/Handler.php
> 
> ```
> public function report(Exception $exception)
> {
>     if (app()->bound('bugphix') && $this->shouldReport($exception)) {
>         app('bugphix')->catchError($exception);
>     }
> 
>     parent::report($exception);
> }
> ```

Replaces "use BugphixSetter, BugphixHelpers;" for "use BugphixSetter;" in the files src/Traits/BugphixSetter.php,
src/Bugphix.php

`src/Traits/BugphixSetter.php on line 13:`
`use BugphixSetter, BugphixHelpers;`
to
`use BugphixSetter;`

`src/Bugphix.php on line 14:`
`use BugphixSetter, BugphixHelpers;`
to
`use BugphixSetter;`
