### ISSUE TITLE
Error with trait methods

### ISSUE THREAD

**Issue by silasrm** [bugphix/bugphix-laravel#9]
**Describe the bug**
PHP Fatal error:  Trait method getEventUrl has not been applied, because there are collisions with PHP Fatal error:  Trait method getEventUrl has not been applied, because there are collisions with other trait methods on Bugphix\BugphixLaravel\Traits\BugphixProcess in /var/www/xxxxxxxxxxxxxxxx/vendor/bugphix/bugphix-laravel/src/Traits/BugphixProcess.php on line 20
PHP Fatal error:  Uncaught Error: Call to undefined method Bugphix\BugphixLaravel\Bugphix::setProject() in /var/www/xxxxxxxxxxxxxxxx/vendor/bugphix/bugphix-laravel/src/Bugphix.php:40
Stack trace:
#0 /var/www/xxxxxxxxxxxxxxxx/app/Exceptions/Handler.php(60): Bugphix\BugphixLaravel\Bugphix->catchError(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /var/www/xxxxxxxxxxxxxxxx/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(60): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 /var/www/xxxxxxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(92): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /var/www/xxxxxxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 [inte in /var/www/xxxxxxxxxxxxxxxx/vendor/bugphix/bugphix-laravel/src/Bugphix.php on line 40

**To Reproduce**
1. Only use last version

**Expected behavior**
Run without error.

**Client / Server details (please complete the following information):**
 - Server OS: Ubuntu Linux
 - Laravel version 6.*

**Comment by rakshitbharat** [comment]
wait for PR merge #11

**Comment by silasrm** [comment]
Thks!
